// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    ALayout: typeof import('ant-design-vue/es')['Layout'];
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
    Header: typeof import('./src/components/header/index.vue')['default'];
    TodoBody: typeof import('./src/components/todo-body/index.vue')['default'];
    TodoFooter: typeof import('./src/components/todo-footer/index.vue')['default'];
    TodoHeader: typeof import('./src/components/todo-header/index.vue')['default'];
  }
}

export {};
